"""removed player reference from history

Revision ID: 2aaca72a9187
Revises: c4e0352ea122
Create Date: 2021-02-20 09:37:35.716697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aaca72a9187'
down_revision = 'c4e0352ea122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('story', sa.String(), nullable=True))
    op.drop_constraint(None, 'history', type_='foreignkey')
    op.drop_column('history', 'player_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('player_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'history', 'user', ['player_id'], ['id'], ondelete='CASCADE')
    op.drop_column('history', 'story')
    # ### end Alembic commands ###
