"""added datetime stamp to history so can sort

Revision ID: e70ade953278
Revises: 11b39ec0b033
Create Date: 2021-05-08 20:16:50.792128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e70ade953278'
down_revision = '11b39ec0b033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('a_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'a_datetime')
    # ### end Alembic commands ###
